print("AlbaOS MC Installer")
print("Install starting...")
print("====================================")
textutils.slowPrint("/////////////////////////////////////")
textutils.slowPrint("Deleteing previous evil os's")
shell.run("delete ","startup")
shell.run("delete","AlbaOS")
shell.run("delete","uninstall")
shell.run("delete",".menu")
shell.run("delete","back")
print("====================================")
sleep(1)
textutils.slowPrint("Installing AlbaOS kernel and utils ...")
shell.run("cp","disk/AlbaOS",".menu")
shell.run("cp","disk/AlbaOS","AlbaOS")
shell.run("cp","disk/AlbaOS","uninstall")
shell.run("cp","disk/AlbaOS","startup")
--programms in AlbaOS/ dir
shell.run("cp","disk/AlbaOS","back")
print("====================================")
textutils.slowPrint("Ejecting AlbaOS Installer ...")
disk.eject("top")
disk.eject("bottom")
disk.eject("left")
disk.eject("right")
disk.eject("front")
disk.eject("back")
textutils.slowPrint("Rebooting ... volare sicut tyto noctua")
sleep(1)
os.reboot()